name: Release Charts on demand

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Release branch'
        required: true

jobs:
  release:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: "${{ github.event.inputs.branch }}"

    - name: Fetch history
      run: git fetch --prune --unshallow

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        cat ./charts/longhorn/Chart.yaml

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.6.0
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
